name: space_news
description: Space Curiosity and all the things realted to the final frontier.

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  ## Online
  cloud_firestore: ^0.9.0+2
  flutter_web_browser: ^0.10.0
  http: ^0.12.0+1
  url_launcher: ^5.0.1
  webfeed: ^0.4.2

  ## Offline
  cached_network_image: ^0.6.0+1
  shared_preferences: ^0.5.1+1

  ## Widgets
  add_2_calendar: ^1.2.1
  flutter_map: ^0.4.0
  flutter_swiper: ^1.1.4
  material_search: ^0.2.8
  native_widgets: ^0.1.1+1
  sliver_fab: ^1.0.0

  ## Tools
  clipboard_manager: ^0.0.4
  equatable: ^0.1.10
  flutter_bloc: ^0.6.2
  flutter_i18n: ^0.5.2
  image_downloader: ^0.11.1
  intl: ^0.15.7
  location: ^2.0.0
  package_info: ^0.4.0+1
  scoped_model: ^1.0.1
  share: ^0.6.0+1

  ## Icons
  font_awesome_flutter: ^8.4.0

flutter:
  fonts:
    - family: RobotoMono
      fonts:
        - asset: assets/fonts/RobotoMono-Bold.ttf
        - asset: assets/fonts/RobotoMono-Italic.ttf
        - asset: assets/fonts/RobotoMono-Regular.ttf
          weight: 700
    - family: ProductSans
      fonts:
        - asset: assets/fonts/ProductSans-Bold.ttf
        - asset: assets/fonts/ProductSans-Italic.ttf
        - asset: assets/fonts/ProductSans-Regular.ttf
          weight: 700
  assets:
    - assets/flutter_i18n/

  uses-material-design: true